#pragma once

#include "Globals.h"

#include "Components/Component.h"
#include "Components/Renderable.h"
#include "Components/Position.h"
#include "Components/Scale.h"
#include "Components/Camera.h"
#include "Components/GameObject.h"
//#include "Components/Container.h"
//#include "Components/GridCell.h"
#include "Components/Coordinate.h"
#include "Components/Container2.h"
#include "Components/Cell.h"
#include "Components/Tag.h"
#include "Components/ReferenceEntity.h"
#include "Components/ScaleToCellDimensions.h"
#include "Components/DerivePositionFromCoordinates.h"
#include "Components/DerivePositionFromParent.h"
#include "Components/Moveable.h"
#include "Components/Controllable.h"
#include "Components/Block.h"
#include "Components/Flag.h"
#include "Components/Hittable.h"
#include "Components/Marker.h"
#include "Components/CellLink.h"
#include "Components/Obstructable.h"
#include "Components/Obstructs.h"

#include "Components/Tetrominos/Tetromino.h"
#include "Components/Tetrominos/OTetromino.h"
#include "Components/Tetrominos/ITetromino.h"
#include "Components/Tetrominos/TTetromino.h"
#include "Components/Tetrominos/LTetromino.h"
#include "Components/Tetrominos/JTetromino.h"
#include "Components/Tetrominos/STetromino.h"
#include "Components/Tetrominos/ZTetromino.h"

#include "Components/Follower.h"
#include "Components/Wall.h"
#include "Components/Rotateable.h"
#include "Components/Orientation.h"
#include "Components/DeriveOrientationFromParent.h"
#include "Components/InheritScalingFromParent.h"

#include "Components/CardinalDirection.h"
#include "Components/SpawnMarker.h"
#include "Components/DirectionallyActive.h"

#include "Components/Bag.h"
#include "Components/QueueNode.h"
#include "Components/NodeOrder.h"

#include "Components/ProjectionOf.h"

#include "Components/UI/UIComponent.h"
#include "Components/UI/UIPosition.h"
#include "Components/UI/UIRenderable.h"
#include "Components/UI/UIOverlay.h"
#include "Components/UI/UIText.h"
#include "Components/UI/UITextLevel.h"
#include "Components/UI/UITextScore.h"

#include "Components/Censor.h"